version: 1
weights:
  instagram:
    base_weight: 20
    format_biases:
      feed_4x5: 3
      reel_9x16: 5
      story_9x16: 2
      carousel_4x5: 4
  facebook:
    base_weight: 5
    format_biases:
      feed_4x5: 3
      link_preview: 2
      reel_9x16: 2
  youtube:
    base_weight: 15
    format_biases:
      longform_16x9: 5
      short_9x16: 4
      community_post: 2
  google_business:
    base_weight: 8
    format_biases:
      post_square: 2
      post_landscape: 2
  mailchimp:
    base_weight: 12
    format_biases:
      campaign_email: 1
  patreon:
    base_weight: 15
    format_biases:
      patron_update: 2
